### ISSUE TITLE
How to extract flow type of an action from an action creator?

### ISSUE THREAD

**Issue by vomchik** [lttb/typed-actions#7]
Hi @lttb.
Thanks for the awesome wrapper for redux-actions.

I have a question.
In my current project, i use redux-saga and i want to add a type of the received action.
I do it something like this:
```
type ReceivedAction<F> = $Call<F, *>;

export function* worker(
  action: ReceivedAction<typeof change>
): Saga<*> {
  // ...
}
```

But maybe you have a much better suggestion for this?
Thanks!

**Comment by lttb** [comment]
Hi @vomchik!

Thanks for the question.

First of all, you can use `ReturnType` from the `typed-actions` this way:

```js
import type {ReturnType} from 'typed-actions'

const action = $Call<ReturnType, typeof actionCreator>
```

It might be helpful too (like yours ReceivedAction), but it'll give you the unnecessary `Return` type wrapper in the final type:

```js
type Return<T> = $Call<ReturnType, T>

const action = Return<typeof actionCreator>
```

But I don't like it too much, because this way you need to work with some of the implementation details and make some `Type work`, which I prefer to avoid in the 'not-a-library' code.

And I don't work with `redux-saga` in general, but I think that it would be better and a bit more readable to declare `Worker` type and use it like:
```js
type Worker<A, T> = $Call<ReturnType, A> => Saga<T>

export const worker: Worker<typeof change, void> = function* (action) {
  // ...
}
```

**Comment by vomchik** [comment]
thanks for the answer!
